# Copyright 2026 August S.H.
# Licensed under the Apache License, Version 2.0
# This file is part of the preemptive-lsm project.
# Not derived from mini-lsm.
# Generated by Claude Code with human guidance and review.
#
# Generates publication-quality figures and tables for a two-column LaTeX report.
#
# Usage:
#   python analysis/plot.py results/docker/experiments_c1.json \
#       results/docker/experiments_c2.json results/docker/experiments_c4.json \
#       --out results/plots

import argparse
import json
import pathlib
import sys

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
    import numpy as np
except ImportError:
    sys.exit("Install matplotlib and numpy: pip install matplotlib numpy")


# ── constants ────────────────────────────────────────────────────────────────

# Two-column LaTeX sizing (inches).
COL_WIDTH = 3.45      # single column
FULL_WIDTH = 7.1      # full text width

# Consistent styling.
COLOR_NY = "#2c3e50"   # NoYield — dark slate
COLOR_CY = "#2980b9"   # ConditionalYield — blue
FONT_SIZE = 8
ROLLING_WINDOW = 10

WORKLOAD_LABELS = {"A": "A (50/50)", "B": "B (95/5 read)",
                   "C": "C (95/5 write)", "D": "D (100% read)"}
WORKLOAD_MARKERS = {"A": "o", "B": "s", "C": "^", "D": "D"}
WORKLOAD_COLORS = {"A": "#e74c3c", "B": "#2980b9", "C": "#27ae60", "D": "#8e44ad"}

plt.rcParams.update({
    "font.size": FONT_SIZE,
    "axes.labelsize": FONT_SIZE,
    "axes.titlesize": FONT_SIZE + 1,
    "xtick.labelsize": FONT_SIZE - 1,
    "ytick.labelsize": FONT_SIZE - 1,
    "legend.fontsize": FONT_SIZE - 1,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.05,
    "lines.linewidth": 1.2,
    "lines.markersize": 4,
})


# ── helpers ──────────────────────────────────────────────────────────────────

def load_results(paths):
    results = []
    for p in paths:
        with open(p) as f:
            batch = json.load(f)
        results.extend(batch)
        print(f"Loaded {len(batch)} records from {p}")
    return results


def _filter(results, **kwargs):
    out = results
    for k, v in kwargs.items():
        out = [r for r in out if r.get(k) == v]
    return out


def _mean_field(records, field):
    vals = [r[field] for r in records if field in r]
    return np.mean(vals) if vals else float("nan")


def _best_interval(results, workload, threads, cores,
                   metric="p999_us", minimize=True):
    """Best ConditionalYield interval for the given config."""
    cands = _filter(results, strategy="ConditionalYield",
                    workload=workload, threads=threads, cores=cores)
    if not cands:
        return None, float("nan")
    best_iv, best_val = None, float("inf") if minimize else float("-inf")
    for iv in sorted({r["yield_interval"] for r in cands}):
        val = _mean_field(_filter(cands, yield_interval=iv), metric)
        if (minimize and val < best_val) or (not minimize and val > best_val):
            best_iv, best_val = iv, val
    return best_iv, best_val


def _rolling_mean(ys, window=ROLLING_WINDOW):
    arr = np.array(ys, dtype=float)
    kernel = np.ones(window) / window
    # Pad to avoid edge effects.
    pad = window // 2
    padded = np.pad(arr, (pad, pad), mode="edge")
    smoothed = np.convolve(padded, kernel, mode="valid")
    return smoothed[:len(arr)]


# ── Figure 1: P99.9 vs yield interval (money plot) ──────────────────────────
# Config: c=1, t=1 (maximum CPU contention). One line per workload.
# NoYield baselines as dashed horizontal lines. Log x-axis.

def fig1_interval_sweep(results, out_dir, cores=1, threads=1):
    workloads = sorted({r["workload"] for r in results})
    intervals = sorted({r["yield_interval"] for r in results
                        if r["strategy"] == "ConditionalYield"})

    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.4))

    for wl in workloads:
        color = WORKLOAD_COLORS[wl]
        marker = WORKLOAD_MARKERS[wl]

        # NoYield baseline
        ny = _filter(results, strategy="NoYield", workload=wl,
                     threads=threads, cores=cores)
        if not ny:
            continue
        baseline = _mean_field(ny, "p999_us")
        ax.axhline(baseline, color=color, linestyle="--", linewidth=0.8,
                   alpha=0.5)

        # ConditionalYield across intervals
        ys = []
        for iv in intervals:
            recs = _filter(results, strategy="ConditionalYield", workload=wl,
                           threads=threads, cores=cores, yield_interval=iv)
            ys.append(_mean_field(recs, "p999_us"))

        ax.plot(intervals, ys, color=color, marker=marker, markersize=4,
                label=WORKLOAD_LABELS[wl])

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Yield interval (entries)")
    ax.set_ylabel("p99.9 latency (\u00b5s)")
    ax.legend(loc="lower left", framealpha=0.9, ncol=1)
    ax.grid(True, alpha=0.2, which="both")
    ax.set_xticks(intervals)
    ax.get_xaxis().set_major_formatter(ticker.ScalarFormatter())

    plt.tight_layout()
    path = out_dir / "fig1_interval_sweep.pdf"
    fig.savefig(path)
    print(f"Saved: {path}")
    plt.close()


# ── Figure 2: Tail-latency CCDF ─────────────────────────────────────────────
# Complementary CDF: x = latency (log), y = 1 - percentile (log).
# Uses the 5 stored percentiles (p50, p95, p99, p999, max) as anchor points.
# Config: c=1, t=1, workload A.

def fig2_ccdf(results, out_dir, cores=1, threads=1, workload="A"):
    ny = _filter(results, strategy="NoYield", workload=workload,
                 threads=threads, cores=cores)
    best_iv, _ = _best_interval(results, workload, threads, cores)
    cy = _filter(results, strategy="ConditionalYield", workload=workload,
                 threads=threads, cores=cores, yield_interval=best_iv)

    if not ny or not cy:
        print("fig2: insufficient data, skipping")
        return

    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.4))

    for recs, label, color, marker in [
        (ny, "NoYield", COLOR_NY, "o"),
        (cy, f"ConditionalYield (iv={best_iv})", COLOR_CY, "^"),
    ]:
        r = recs[0]
        cdf_data = r.get("cdf", [])
        if cdf_data:
            # Use sampled CDF data (list of [quantile, latency_us]).
            qs = np.array([pt[0] for pt in cdf_data])
            xs = np.array([pt[1] for pt in cdf_data])
            tail = 1.0 - qs
            # Only plot the tail region (above p90) where differences matter.
            mask = qs >= 0.50
            ax.plot(xs[mask], tail[mask], color=color, linewidth=1.5,
                    label=label)
        else:
            # Fallback: use the 4 stored percentile points.
            quantiles = [0.50, 0.95, 0.99, 0.999]
            fields = ["p50_us", "p95_us", "p99_us", "p999_us"]
            xs = [r[f] for f in fields]
            tail = [1 - q for q in quantiles]
            ax.plot(xs, tail, color=color, marker=marker, markersize=5,
                    linewidth=1.5, label=label)

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Latency (\u00b5s)")
    ax.set_ylabel("P(latency > x)")
    ax.legend(loc="lower left", framealpha=0.9)
    ax.grid(True, alpha=0.2, which="both")
    ax.set_title(f"Workload {WORKLOAD_LABELS[workload]}, c={cores}, t={threads}")

    plt.tight_layout()
    path = out_dir / "fig2_ccdf.pdf"
    fig.savefig(path)
    print(f"Saved: {path}")
    plt.close()


# ── Figure 3: Time-series P99.9 ─────────────────────────────────────────────
# Per-second p99.9 over 60 s for NoYield vs best ConditionalYield.
# Scatter + rolling mean. Config: c=1, t=1, workload A.

def fig3_time_series(results, out_dir, cores=1, threads=1, workload="A"):
    ts_results = [r for r in results if r.get("time_series")]

    ny = _filter(ts_results, strategy="NoYield", workload=workload,
                 threads=threads, cores=cores)
    best_iv, _ = _best_interval(results, workload, threads, cores)
    cy = _filter(ts_results, strategy="ConditionalYield", workload=workload,
                 threads=threads, cores=cores, yield_interval=best_iv)

    if not ny or not cy:
        print("fig3: insufficient data, skipping")
        return

    fig, ax = plt.subplots(figsize=(FULL_WIDTH, 2.2))

    for recs, label, color in [
        (ny, "NoYield", COLOR_NY),
        (cy, f"ConditionalYield (iv={best_iv})", COLOR_CY),
    ]:
        ts = recs[0].get("time_series", [])
        if not ts:
            continue
        xs = np.array([pt["elapsed_secs"] for pt in ts])
        ys = np.array([pt["p999_us"] for pt in ts])

        ax.scatter(xs, ys, color=color, alpha=0.12, s=4, linewidths=0)
        trend = _rolling_mean(ys)
        ax.plot(xs, trend, color=color, linewidth=1.5, label=label)

    ax.set_yscale("log")
    ax.set_xlabel("Elapsed time (s)")
    ax.set_ylabel("p99.9 latency (\u00b5s)")
    ax.legend(loc="lower right", framealpha=0.9)
    ax.grid(True, alpha=0.2, which="both")
    ax.set_title(f"Workload {WORKLOAD_LABELS[workload]}, c={cores}, t={threads}")

    plt.tight_layout()
    path = out_dir / "fig3_time_series.pdf"
    fig.savefig(path)
    print(f"Saved: {path}")
    plt.close()


# ── Figure 4: CPU contention effect ─────────────────────────────────────────
# Fix workload and thread count. Paired bars (NoYield vs best CY) grouped
# by CPU core count. Shows diminishing benefit as contention decreases.

def fig4_cpu_contention(results, out_dir, workload="A", threads=1):
    core_counts = sorted({r["cores"] for r in results})

    ny_vals = []
    cy_vals = []
    cy_labels = []
    for cc in core_counts:
        ny = _filter(results, strategy="NoYield", workload=workload,
                     threads=threads, cores=cc)
        ny_vals.append(_mean_field(ny, "p999_us"))

        best_iv, best_val = _best_interval(results, workload, threads, cc)
        cy_vals.append(best_val)
        cy_labels.append(f"iv={best_iv}")

    x = np.arange(len(core_counts))
    w = 0.35

    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.4))
    bars_ny = ax.bar(x - w / 2, ny_vals, w, label="NoYield", color=COLOR_NY,
                     alpha=0.85)
    bars_cy = ax.bar(x + w / 2, cy_vals, w, label="ConditionalYield",
                     color=COLOR_CY, alpha=0.85)

    ax.set_yscale("log")

    # Annotate % change inside the NoYield bars.
    for i, (nyv, cyv) in enumerate(zip(ny_vals, cy_vals)):
        if nyv > 0 and not np.isnan(cyv):
            pct = (cyv - nyv) / nyv * 100
            # Place inside the NoYield bar at geometric midpoint.
            ymin_bar = ax.get_ylim()[0] if ax.get_ylim()[0] > 0 else 1
            ypos = np.sqrt(nyv * max(ymin_bar, cyv))
            ax.text(x[i] - w / 2, ypos, f"{pct:+.0f}%", ha="center",
                    va="center", fontsize=FONT_SIZE, fontweight="bold",
                    color="white",
                    bbox=dict(boxstyle="round,pad=0.15", fc="black",
                              alpha=0.5, lw=0))

    ax.set_xticks(x)
    ax.set_xticklabels([f"{cc} core{'s' if cc > 1 else ''}" for cc in core_counts])
    ax.set_ylabel("p99.9 latency (\u00b5s)")
    ax.legend(loc="upper right", framealpha=0.9)
    ax.grid(True, axis="y", alpha=0.2, which="both")
    ax.set_title(f"Workload {WORKLOAD_LABELS[workload]}, t={threads}")

    plt.tight_layout()
    path = out_dir / "fig4_cpu_contention.pdf"
    fig.savefig(path)
    print(f"Saved: {path}")
    plt.close()


# ── Table 1: Summary across workloads ────────────────────────────────────────
# One row per workload. Columns: p50/p95/p99/p999 for NoYield and CY,
# p99.9 % improvement, throughput. Fixed config: c=1, t=1.

def table1_summary(results, out_dir, cores=1, threads=1):
    workloads = sorted({r["workload"] for r in results})
    fields = ["p50_us", "p95_us", "p99_us", "p999_us"]
    field_labels = ["p50", "p95", "p99", "p99.9"]

    lines = []
    lines.append(f"% Table 1: Latency summary (c={cores}, t={threads})")
    lines.append(r"\begin{tabular}{l" + " r" * 4 + " r" * 4 + " r r}")
    lines.append(r"\toprule")

    header1 = r"& \multicolumn{4}{c}{NoYield (\textmu s)}"
    header1 += r" & \multicolumn{4}{c}{ConditionalYield (\textmu s)}"
    header1 += r" & p99.9 & Throughput \\"
    lines.append(header1)

    header2 = "WL"
    for _ in range(2):
        for fl in field_labels:
            header2 += f" & {fl}"
    header2 += r" & \% $\Delta$ & $\Delta$ \\"
    lines.append(header2)
    lines.append(r"\midrule")

    for wl in workloads:
        ny = _filter(results, strategy="NoYield", workload=wl,
                     threads=threads, cores=cores)
        best_iv, _ = _best_interval(results, wl, threads, cores)
        cy = _filter(results, strategy="ConditionalYield", workload=wl,
                     threads=threads, cores=cores, yield_interval=best_iv)

        if not ny or not cy:
            continue

        row = wl
        ny_r, cy_r = ny[0], cy[0]

        for r in [ny_r, cy_r]:
            for f in fields:
                val = r[f]
                if val >= 1000:
                    row += f" & {val:,.0f}"
                elif val >= 10:
                    row += f" & {val:.1f}"
                else:
                    row += f" & {val:.2f}"

        # p999 % change
        ny_p999 = ny_r["p999_us"]
        cy_p999 = cy_r["p999_us"]
        pct = (cy_p999 - ny_p999) / ny_p999 * 100 if ny_p999 > 0 else 0
        row += f" & {pct:+.1f}\\%"

        # Throughput % change
        ny_tp = ny_r["throughput_ops"]
        cy_tp = cy_r["throughput_ops"]
        tp_pct = (cy_tp - ny_tp) / ny_tp * 100 if ny_tp > 0 else 0
        row += f" & {tp_pct:+.1f}\\%"

        row += r" \\"
        lines.append(row)

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    text = "\n".join(lines)
    path = out_dir / "table1_summary.tex"
    with open(path, "w") as f:
        f.write(text + "\n")
    print(f"Saved: {path}")
    print(text)


# ── Table 2: Throughput cost ─────────────────────────────────────────────────
# Throughput for NoYield vs each yield interval. One workload, c=1, t=1.

def table2_throughput(results, out_dir, cores=1, threads=1, workload="A"):
    intervals = sorted({r["yield_interval"]
                        for r in results if r["strategy"] == "ConditionalYield"})

    ny = _filter(results, strategy="NoYield", workload=workload,
                 threads=threads, cores=cores)
    if not ny:
        return
    ny_tp = ny[0]["throughput_ops"]
    ny_p999 = ny[0]["p999_us"]

    lines = []
    lines.append(f"% Table 2: Throughput cost (Workload {workload}, c={cores}, t={threads})")
    lines.append(r"\begin{tabular}{l r r r r}")
    lines.append(r"\toprule")
    lines.append(r"Strategy & Interval & Throughput & Thr. $\Delta$ & p99.9 $\Delta$ \\")
    lines.append(r"\midrule")

    lines.append(f"NoYield & --- & {ny_tp:,.0f} & --- & --- \\\\")

    for iv in intervals:
        recs = _filter(results, strategy="ConditionalYield", workload=workload,
                       threads=threads, cores=cores, yield_interval=iv)
        if not recs:
            continue
        r = recs[0]
        tp = r["throughput_ops"]
        tp_pct = (tp - ny_tp) / ny_tp * 100
        p999 = r["p999_us"]
        p999_pct = (p999 - ny_p999) / ny_p999 * 100
        lines.append(f"CY & {iv:,} & {tp:,.0f} & {tp_pct:+.1f}\\% & {p999_pct:+.1f}\\% \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    text = "\n".join(lines)
    path = out_dir / "table2_throughput.tex"
    with open(path, "w") as f:
        f.write(text + "\n")
    print(f"Saved: {path}")
    print(text)


# ── entry point ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate figures and tables for the preemptive-lsm report."
    )
    parser.add_argument(
        "inputs", nargs="+", metavar="results.json",
        help="One or more benchmark result JSON files",
    )
    parser.add_argument(
        "--cdf", nargs="*", metavar="cdf.json",
        help="Separate CDF result JSON files (with sampled quantile data)",
    )
    parser.add_argument(
        "--out", default="results/plots", metavar="dir",
        help="Output directory (default: results/plots)",
    )
    args = parser.parse_args()

    out_dir = pathlib.Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    results = load_results(args.inputs)
    cdf_results = load_results(args.cdf) if args.cdf else None
    print(f"\nTotal: {len(results)} records")
    print(f"  Strategies: {sorted({r['strategy'] for r in results})}")
    print(f"  Workloads:  {sorted({r['workload'] for r in results})}")
    print(f"  Threads:    {sorted({r['threads'] for r in results})}")
    print(f"  Cores:      {sorted({r['cores'] for r in results})}")
    print()

    # Primary config: c=1, t=1 (maximum CPU contention).
    C, T = 1, 1

    fig1_interval_sweep(results, out_dir, cores=C, threads=T)
    fig2_ccdf(cdf_results or results, out_dir, cores=C, threads=T, workload="A")
    fig3_time_series(results, out_dir, cores=C, threads=T, workload="A")
    fig4_cpu_contention(results, out_dir, workload="A", threads=T)
    table1_summary(results, out_dir, cores=C, threads=T)
    table2_throughput(results, out_dir, cores=C, threads=T, workload="A")


if __name__ == "__main__":
    main()